import pandas as pd
import matplotlib.pyplot as plt
tabela = pd.read_excel("PLANILHA Anuário Brasileiro de Segurança Pública 2024.xlsx", sheet_name="Copia T43")

#print(tabela)

x = tabela.columns[1:7].tolist()

yCeara = tabela.iloc[5, 1:7].tolist()

fig, ax = plt.subplots()
barras = ax.bar(x, yCeara, width=0.5)
ax.bar_label(barras)
plt.title("Número de casos com armas de fogo no Ceará")
plt.xlabel("Anos")
plt.ylabel("Valores")
plt.show()

yAcre = tabela.iloc[0, 1:7].tolist()
yAlagoas = tabela.iloc[1, 1:7].tolist()
yAmapa = tabela.iloc[2, 1:7].tolist()
yAmazonas = tabela.iloc[3, 1:7].tolist()
yBahia = tabela.iloc[4, 1:7].tolist()
yDF = tabela.iloc[6, 1:7].tolist()
yES = tabela.iloc[7, 1:7].tolist()
yGoias = tabela.iloc[8, 1:7].tolist()
yMaranhao = tabela.iloc[9, 1:7].tolist()
yMT = tabela.iloc[10, 1:7].tolist()
yMS = tabela.iloc[11, 1:7].tolist()
yMG = tabela.iloc[12, 1:7].tolist()
yPara = tabela.iloc[13, 1:7].tolist()
yParaiba = tabela.iloc[14, 1:7].tolist()
yParana = tabela.iloc[15, 1:7].tolist()
yPernambuco = tabela.iloc[16, 1:7].tolist()
yPiaui = tabela.iloc[17, 1:7].tolist()
yRJ = tabela.iloc[18, 1:7].tolist()
yRN = tabela.iloc[19, 1:7].tolist()
yRS = tabela.iloc[20, 1:7].tolist()
yRondonia = tabela.iloc[21, 1:7].tolist()
yRoraima = tabela.iloc[22, 1:7].tolist()
ySC = tabela.iloc[23, 1:7].tolist()
ySP = tabela.iloc[24, 1:7].tolist()
ySergipe = tabela.iloc[25, 1:7].tolist()
yTocantins = tabela.iloc[26, 1:7].tolist()

fig, ax = plt.subplots(figsize=(7,7))
plt.plot(x, yAcre, c="green", label="Acre", alpha=0.6)
plt.plot(x, yAlagoas, c="blue", label="Alagoas", alpha=0.6)
plt.plot(x, yAmapa, c="orange", label="Amapa", alpha=0.6)
plt.plot(x, yAmazonas, c="purple", label="Amazonas", alpha=0.6)
plt.plot(x, yBahia, c="brown", label="Bahia", alpha=0.6)
plt.plot(x, yCeara, c="red", label="Ceará")
plt.plot(x, yDF, c="black", label="Distrito Federal", alpha=0.6)
plt.plot(x, yES, c="gray", label="Espírito Santo" ,alpha=0.6)
plt.plot(x, yGoias, c="yellow", label="Goias", alpha=0.6)
plt.plot(x, yMaranhao, c="olive", label="Maranhao" ,alpha=0.6)
plt.plot(x, yMT, c="pink" ,label="Mato Grosso", alpha=0.6)
plt.plot(x, yMS, c="gold", label="Mato Grosso do Sul", alpha=0.6)
plt.plot(x, yMG, c="teal", label="Minas Gerais", alpha=0.6)
plt.plot(x, yPara, c="navy", label="Para", alpha=0.6)
plt.plot(x, yParaiba, c="magenta", label="Paraiba", alpha=0.6)
plt.plot(x, yAcre, c="green")
plt.plot(x, yAcre, c="green")
plt.plot(x, yAcre, c="green")
plt.plot(x, yAcre, c="green")
plt.plot(x, yAcre, c="green")
plt.plot(x, yAcre, c="green")
plt.plot(x, yAcre, c="green")
plt.plot(x, yAcre, c="green")
plt.plot(x, yAcre, c="green")
plt.plot(x, yAcre, c="green")
plt.plot(x, yAcre, c="green")
plt.legend()
plt.show()
