import pandas as pd
import matplotlib.pyplot as plt
import random as rd
tabela = pd.read_excel("PLANILHA Anuário Brasileiro de Segurança Pública 2024.xlsx", sheet_name="Copia T43")

#print(tabela)

tabelaCrescente = tabela.sort_values(by="Total", ascending=False)

x = tabela.columns[1:7].tolist()
xEstados = tabelaCrescente.iloc[1:,0].tolist()
yCeara = tabela.iloc[5, 1:7].tolist()
yTotal = tabelaCrescente.iloc[1:,-1].tolist()

fig, axs = plt.subplots(1,2, figsize=(12, 6))
barras = axs[0].bar(x, yCeara, width=0.5)
axs[0].set_title("Gráfico do número de casos no Ceará")
axs[0].bar_label(barras)
barrash = axs[1].barh(xEstados, yTotal, color="skyblue", edgecolor="black")
axs[1].set_title("Gráfico com o número de casos de cada estado")
axs[1].bar_label(barrash)
axs[0].set_xlabel("Anos")
axs[0].set_ylabel("Valores")
axs[1].set_xlabel("Estados")
axs[1].set_ylabel("Valores")
plt.tight_layout(pad=5)
plt.show()
'''
yAcre = tabela.iloc[0, 1:7].tolist()
yAlagoas = tabela.iloc[1, 1:7].tolist()
yAmapa = tabela.iloc[2, 1:7].tolist()
yAmazonas = tabela.iloc[3, 1:7].tolist()
yBahia = tabela.iloc[4, 1:7].tolist()
yDF = tabela.iloc[6, 1:7].tolist()
yES = tabela.iloc[7, 1:7].tolist()
yGoias = tabela.iloc[8, 1:7].tolist()
yMaranhao = tabela.iloc[9, 1:7].tolist()
yMT = tabela.iloc[10, 1:7].tolist()
yMS = tabela.iloc[11, 1:7].tolist()
yMG = tabela.iloc[12, 1:7].tolist()
yPara = tabela.iloc[13, 1:7].tolist()
yParaiba = tabela.iloc[14, 1:7].tolist()
yParana = tabela.iloc[15, 1:7].tolist()
yPernambuco = tabela.iloc[16, 1:7].tolist()
yPiaui = tabela.iloc[17, 1:7].tolist()
yRJ = tabela.iloc[18, 1:7].tolist()
yRN = tabela.iloc[19, 1:7].tolist()
yRS = tabela.iloc[20, 1:7].tolist()
yRondonia = tabela.iloc[21, 1:7].tolist()
yRoraima = tabela.iloc[22, 1:7].tolist()
ySC = tabela.iloc[23, 1:7].tolist()
ySP = tabela.iloc[24, 1:7].tolist()
ySergipe = tabela.iloc[25, 1:7].tolist()
yTocantins = tabela.iloc[26, 1:7].tolist()

fig, ax = plt.subplots(figsize=(8,8))
plt.plot(x, ySP, label="São Paulo", c="grey")
plt.plot(x, yDF, label="Distrito Federal", c="blue")
plt.plot(x, yRS, label="Rio Grande do Sul", c="pink")
plt.plot(x, yMG, label="Minas Gerais", c="yellow")
plt.plot(x, ySC, label="Santa Catarina", c="green")
plt.plot(x, yParana, label="Paraná", c="purple")
plt.plot(x, yRJ, label="Rio de Janeiro", c="red")
plt.plot(x, yCeara, label="Ceará", c="black")
plt.title("Top 7 estados com o maior número de registros de armas de fogo ativos em comparação com o Ceará")
plt.xlabel("Anos")
plt.ylabel("Quantidades")
plt.legend()
plt.show()'''
cores = []
while(len(cores) != 28):
    cor = (rd.randint(0, 255)/255, rd.randint(0, 255)/255, rd.randint(0, 255)/255)
    cores.append(cor)

fig, ax = plt.subplots(figsize=(10,7))
plt.pie(yTotal, colors=cores, autopct="%1.1f%%", pctdistance=1.3, labeldistance=1.2)
plt.legend(xEstados, loc="upper right", handlelength=0.5, handleheight=0.5, bbox_to_anchor=(1.5,1.1))
plt.show()


